// Code generated by stanc v2.39.0
#include <stan/model/model_header.hpp>
namespace hmeta_uncertainty_model_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 100> locations_array__ =
  {" (found before start of program)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 101, column 4 to column 15)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 102, column 4 to column 27)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 103, column 4 to column 23)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 105, column 4 to column 15)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 106, column 4 to column 27)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 107, column 4 to column 23)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 110, column 4 to column 19)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 111, column 4 to column 30)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 112, column 4 to column 31)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 113, column 4 to column 27)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 118, column 4 to column 36)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 122, column 4 to column 47)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 123, column 4 to column 47)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 124, column 4 to column 22)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 232, column 4 to column 36)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 127, column 8 to line 129, column 50)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 130, column 8 to column 28)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 126, column 23 to line 131, column 5)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 126, column 4 to line 131, column 5)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 135, column 4 to column 33)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 136, column 4 to column 38)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 139, column 4 to column 30)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 140, column 4 to column 32)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 141, column 4 to column 30)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 143, column 4 to column 30)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 144, column 4 to column 32)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 145, column 4 to column 30)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 149, column 4 to column 32)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 150, column 4 to column 32)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 151, column 4 to column 34)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 152, column 4 to column 32)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 156, column 4 to column 29)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 160, column 8 to column 24)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 161, column 8 to column 24)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 162, column 8 to column 25)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 165, column 8 to column 30)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 166, column 8 to column 30)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 169, column 15 to column 23)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 169, column 8 to column 58)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 170, column 15 to column 23)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 170, column 8 to column 58)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 171, column 15 to column 23)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 171, column 8 to column 58)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 172, column 15 to column 23)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 172, column 8 to column 58)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 175, column 12 to column 49)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 178, column 12 to column 56)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 179, column 12 to column 66)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 182, column 12 to column 56)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 183, column 12 to column 66)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 188, column 12 to column 51)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 189, column 12 to column 41)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 190, column 12 to column 51)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 191, column 12 to column 41)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 198, column 16 to column 92)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 199, column 16 to column 92)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 200, column 16 to column 92)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 201, column 16 to column 92)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 203, column 16 to column 59)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 204, column 16 to column 59)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 211, column 16 to column 63)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 212, column 16 to column 63)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 213, column 16 to column 63)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 214, column 16 to column 63)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 193, column 34 to line 215, column 13)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 193, column 12 to line 215, column 13)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 174, column 26 to line 216, column 9)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 174, column 8 to line 216, column 9)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 219, column 8 to line 220, column 83)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 221, column 8 to line 222, column 84)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 223, column 8 to line 224, column 83)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 225, column 8 to line 226, column 83)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 159, column 23 to line 227, column 5)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 159, column 4 to line 227, column 5)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 72, column 4 to column 23)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 73, column 4 to column 26)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 74, column 10 to column 15)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 74, column 17 to column 29)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 74, column 4 to column 49)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 75, column 4 to column 22)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 81, column 4 to column 22)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 84, column 4 to column 23)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 85, column 11 to column 16)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 85, column 18 to column 23)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 85, column 4 to column 31)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 88, column 4 to column 22)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 89, column 11 to column 15)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 89, column 4 to column 26)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 90, column 11 to column 15)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 90, column 4 to column 28)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 96, column 4 to column 24)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 103, column 11 to column 16)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 107, column 11 to column 16)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 111, column 11 to column 16)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 113, column 11 to column 16)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 118, column 12 to column 24)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 122, column 11 to column 16)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 123, column 11 to column 16)",
  " (in '/Users/saurabhext/Documents/metasignal/src/metasignal/sdtbayes/stan/hmeta_uncertainty.stan', line 124, column 11 to column 16)"};
class hmeta_uncertainty_model final : public model_base_crtp<hmeta_uncertainty_model> {
 private:
  int nsubj;
  int nratings;
  std::vector<std::vector<int>> hmetad_counts;
  double Tol;
  double eps;
  int p_cov;
  Eigen::Matrix<double,-1,-1> X_cov_data__;
  int n_gh;
  Eigen::Matrix<double,-1,1> gh_nodes_data__;
  Eigen::Matrix<double,-1,1> gh_weights_data__;
  double delta;
  int log_theta_1dim__;
  Eigen::Map<Eigen::Matrix<double,-1,-1>> X_cov{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> gh_nodes{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> gh_weights{nullptr, 0};
 public:
  ~hmeta_uncertainty_model() {}
  hmeta_uncertainty_model(stan::io::var_context& context__, unsigned int
                          random_seed__ = 0, std::ostream*
                          pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    using local_scalar_t__ = double;
    auto base_rng__ = stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "hmeta_uncertainty_model_namespace::hmeta_uncertainty_model";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 75;
      context__.validate_dims("data initialization", "nsubj", "int",
        std::vector<size_t>{});
      nsubj = std::numeric_limits<int>::min();
      current_statement__ = 75;
      nsubj = context__.vals_i("nsubj")[(1 - 1)];
      current_statement__ = 75;
      stan::math::check_greater_or_equal(function__, "nsubj", nsubj, 1);
      current_statement__ = 76;
      context__.validate_dims("data initialization", "nratings", "int",
        std::vector<size_t>{});
      nratings = std::numeric_limits<int>::min();
      current_statement__ = 76;
      nratings = context__.vals_i("nratings")[(1 - 1)];
      current_statement__ = 76;
      stan::math::check_greater_or_equal(function__, "nratings", nratings, 2);
      current_statement__ = 77;
      stan::math::validate_non_negative_index("hmetad_counts", "nsubj", nsubj);
      current_statement__ = 78;
      stan::math::validate_non_negative_index("hmetad_counts",
        "nratings * 4", (nratings * 4));
      current_statement__ = 79;
      context__.validate_dims("data initialization", "hmetad_counts", "int",
        std::vector<size_t>{static_cast<size_t>(nsubj),
          static_cast<size_t>((nratings * 4))});
      hmetad_counts = std::vector<std::vector<int>>(nsubj,
                        std::vector<int>((nratings * 4),
                          std::numeric_limits<int>::min()));
      {
        std::vector<int> hmetad_counts_flat__;
        current_statement__ = 79;
        hmetad_counts_flat__ = context__.vals_i("hmetad_counts");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= (nratings * 4); ++sym1__) {
          for (int sym2__ = 1; sym2__ <= nsubj; ++sym2__) {
            stan::model::assign(hmetad_counts, hmetad_counts_flat__[(pos__ -
              1)], "assigning variable hmetad_counts",
              stan::model::index_uni(sym2__), stan::model::index_uni(sym1__));
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 80;
      context__.validate_dims("data initialization", "Tol", "double",
        std::vector<size_t>{});
      Tol = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 80;
      Tol = context__.vals_r("Tol")[(1 - 1)];
      current_statement__ = 80;
      stan::math::check_greater_or_equal(function__, "Tol", Tol, 0);
      current_statement__ = 81;
      context__.validate_dims("data initialization", "eps", "double",
        std::vector<size_t>{});
      eps = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 81;
      eps = context__.vals_r("eps")[(1 - 1)];
      current_statement__ = 81;
      stan::math::check_greater_or_equal(function__, "eps", eps, 0);
      current_statement__ = 82;
      context__.validate_dims("data initialization", "p_cov", "int",
        std::vector<size_t>{});
      p_cov = std::numeric_limits<int>::min();
      current_statement__ = 82;
      p_cov = context__.vals_i("p_cov")[(1 - 1)];
      current_statement__ = 82;
      stan::math::check_greater_or_equal(function__, "p_cov", p_cov, 0);
      current_statement__ = 83;
      stan::math::validate_non_negative_index("X_cov", "nsubj", nsubj);
      current_statement__ = 84;
      stan::math::validate_non_negative_index("X_cov", "p_cov", p_cov);
      current_statement__ = 85;
      context__.validate_dims("data initialization", "X_cov", "double",
        std::vector<size_t>{static_cast<size_t>(nsubj),
          static_cast<size_t>(p_cov)});
      X_cov_data__ = Eigen::Matrix<double,-1,-1>::Constant(nsubj, p_cov,
                       std::numeric_limits<double>::quiet_NaN());
      new (&X_cov)
        Eigen::Map<Eigen::Matrix<double,-1,-1>>(X_cov_data__.data(), nsubj,
        p_cov);
      {
        std::vector<local_scalar_t__> X_cov_flat__;
        current_statement__ = 85;
        X_cov_flat__ = context__.vals_r("X_cov");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= p_cov; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= nsubj; ++sym2__) {
            stan::model::assign(X_cov, X_cov_flat__[(pos__ - 1)],
              "assigning variable X_cov", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 86;
      context__.validate_dims("data initialization", "n_gh", "int",
        std::vector<size_t>{});
      n_gh = std::numeric_limits<int>::min();
      current_statement__ = 86;
      n_gh = context__.vals_i("n_gh")[(1 - 1)];
      current_statement__ = 86;
      stan::math::check_greater_or_equal(function__, "n_gh", n_gh, 1);
      current_statement__ = 87;
      stan::math::validate_non_negative_index("gh_nodes", "n_gh", n_gh);
      current_statement__ = 88;
      context__.validate_dims("data initialization", "gh_nodes", "double",
        std::vector<size_t>{static_cast<size_t>(n_gh)});
      gh_nodes_data__ = Eigen::Matrix<double,-1,1>::Constant(n_gh,
                          std::numeric_limits<double>::quiet_NaN());
      new (&gh_nodes)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(gh_nodes_data__.data(), n_gh);
      {
        std::vector<local_scalar_t__> gh_nodes_flat__;
        current_statement__ = 88;
        gh_nodes_flat__ = context__.vals_r("gh_nodes");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= n_gh; ++sym1__) {
          stan::model::assign(gh_nodes, gh_nodes_flat__[(pos__ - 1)],
            "assigning variable gh_nodes", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 89;
      stan::math::validate_non_negative_index("gh_weights", "n_gh", n_gh);
      current_statement__ = 90;
      context__.validate_dims("data initialization", "gh_weights", "double",
        std::vector<size_t>{static_cast<size_t>(n_gh)});
      gh_weights_data__ = Eigen::Matrix<double,-1,1>::Constant(n_gh,
                            std::numeric_limits<double>::quiet_NaN());
      new (&gh_weights)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(gh_weights_data__.data(),
        n_gh);
      {
        std::vector<local_scalar_t__> gh_weights_flat__;
        current_statement__ = 90;
        gh_weights_flat__ = context__.vals_r("gh_weights");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= n_gh; ++sym1__) {
          stan::model::assign(gh_weights, gh_weights_flat__[(pos__ - 1)],
            "assigning variable gh_weights", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 91;
      context__.validate_dims("data initialization", "delta", "double",
        std::vector<size_t>{});
      delta = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 91;
      delta = context__.vals_r("delta")[(1 - 1)];
      current_statement__ = 91;
      stan::math::check_greater_or_equal(function__, "delta", delta, 0);
      current_statement__ = 92;
      stan::math::validate_non_negative_index("d1_z", "nsubj", nsubj);
      current_statement__ = 93;
      stan::math::validate_non_negative_index("c1_z", "nsubj", nsubj);
      current_statement__ = 94;
      stan::math::validate_non_negative_index("beta_logPhi", "p_cov", p_cov);
      current_statement__ = 95;
      stan::math::validate_non_negative_index("logPhi_z", "nsubj", nsubj);
      current_statement__ = 96;
      log_theta_1dim__ = std::numeric_limits<int>::min();
      current_statement__ = 96;
      log_theta_1dim__ = (nratings - 1);
      current_statement__ = 96;
      stan::math::validate_non_negative_index("log_theta", "nratings - 1",
        log_theta_1dim__);
      current_statement__ = 97;
      stan::math::validate_non_negative_index("d1", "nsubj", nsubj);
      current_statement__ = 98;
      stan::math::validate_non_negative_index("c1", "nsubj", nsubj);
      current_statement__ = 99;
      stan::math::validate_non_negative_index("phi", "nsubj", nsubj);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1 + 1 + nsubj + 1 + 1 + nsubj + 1 + p_cov + 1 + nsubj +
      log_theta_1dim__;
  }
  inline std::string model_name() const final {
    return "hmeta_uncertainty_model";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.39.0",
             "stancflags = "};
  }
  // Base log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_not_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "hmeta_uncertainty_model_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      current_statement__ = 1;
      auto mu_d1 = in__.template read<local_scalar_t__>();
      current_statement__ = 2;
      auto sigma_d1 =
        in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
          lp__);
      current_statement__ = 3;
      auto d1_z =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(nsubj);
      current_statement__ = 4;
      auto mu_c1 = in__.template read<local_scalar_t__>();
      current_statement__ = 5;
      auto sigma_c1 =
        in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
          lp__);
      current_statement__ = 6;
      auto c1_z =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(nsubj);
      current_statement__ = 7;
      auto mu_logPhi = in__.template read<local_scalar_t__>();
      current_statement__ = 8;
      auto beta_logPhi =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(p_cov);
      current_statement__ = 9;
      auto sigma_logPhi =
        in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
          lp__);
      current_statement__ = 10;
      auto logPhi_z =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(nsubj);
      current_statement__ = 11;
      auto log_theta =
        in__.template read_constrain_ordered<
          Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(lp__,
          log_theta_1dim__);
      Eigen::Matrix<local_scalar_t__,-1,1> d1 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nsubj, DUMMY_VAR__);
      current_statement__ = 12;
      stan::model::assign(d1,
        stan::math::add(mu_d1, stan::math::multiply(sigma_d1, d1_z)),
        "assigning variable d1");
      Eigen::Matrix<local_scalar_t__,-1,1> c1 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nsubj, DUMMY_VAR__);
      current_statement__ = 13;
      stan::model::assign(c1,
        stan::math::add(mu_c1, stan::math::multiply(sigma_c1, c1_z)),
        "assigning variable c1");
      Eigen::Matrix<local_scalar_t__,-1,1> phi =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nsubj, DUMMY_VAR__);
      current_statement__ = 19;
      for (int s = 1; s <= nsubj; ++s) {
        local_scalar_t__ eta_s = DUMMY_VAR__;
        current_statement__ = 16;
        eta_s = ((mu_logPhi +
          stan::math::dot_product(beta_logPhi,
            stan::math::transpose(
              stan::model::rvalue(X_cov, "X_cov", stan::model::index_uni(s)))))
          + (sigma_logPhi *
          stan::model::rvalue(logPhi_z, "logPhi_z", stan::model::index_uni(s))));
        current_statement__ = 17;
        stan::model::assign(phi, stan::math::exp(eta_s),
          "assigning variable phi", stan::model::index_uni(s));
      }
      {
        local_scalar_t__ sqrt2 = DUMMY_VAR__;
        current_statement__ = 20;
        sqrt2 = stan::math::sqrt(2.0);
        local_scalar_t__ inv_sqrt_pi = DUMMY_VAR__;
        current_statement__ = 21;
        inv_sqrt_pi = stan::math::inv_sqrt(stan::math::pi());
        current_statement__ = 22;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(mu_d1,
                         static_cast<double>(1), static_cast<double>(2)));
        current_statement__ = 23;
        lp_accum__.add(stan::math::exponential_lpdf<propto__>(sigma_d1,
                         static_cast<double>(1)));
        current_statement__ = 24;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(d1_z,
                         static_cast<double>(0), static_cast<double>(1)));
        current_statement__ = 25;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(mu_c1,
                         static_cast<double>(0), static_cast<double>(1)));
        current_statement__ = 26;
        lp_accum__.add(stan::math::exponential_lpdf<propto__>(sigma_c1,
                         static_cast<double>(1)));
        current_statement__ = 27;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(c1_z,
                         static_cast<double>(0), static_cast<double>(1)));
        current_statement__ = 28;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(mu_logPhi,
                         static_cast<double>(0), static_cast<double>(1)));
        current_statement__ = 29;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(beta_logPhi,
                         static_cast<double>(0), static_cast<double>(1)));
        current_statement__ = 30;
        lp_accum__.add(stan::math::exponential_lpdf<propto__>(sigma_logPhi,
                         static_cast<double>(1)));
        current_statement__ = 31;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(logPhi_z,
                         static_cast<double>(0), static_cast<double>(1)));
        current_statement__ = 32;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(log_theta,
                         static_cast<double>(0), static_cast<double>(1)));
        current_statement__ = 74;
        for (int s = 1; s <= nsubj; ++s) {
          local_scalar_t__ d = DUMMY_VAR__;
          current_statement__ = 33;
          d = stan::model::rvalue(d1, "d1", stan::model::index_uni(s));
          local_scalar_t__ c = DUMMY_VAR__;
          current_statement__ = 34;
          c = stan::model::rvalue(c1, "c1", stan::model::index_uni(s));
          local_scalar_t__ p = DUMMY_VAR__;
          current_statement__ = 35;
          p = stan::model::rvalue(phi, "phi", stan::model::index_uni(s));
          local_scalar_t__ mu_S1 = DUMMY_VAR__;
          current_statement__ = 36;
          mu_S1 = (-(d) / 2.0);
          local_scalar_t__ mu_S2 = DUMMY_VAR__;
          current_statement__ = 37;
          mu_S2 = (d / 2.0);
          current_statement__ = 38;
          stan::math::validate_non_negative_index("prCR", "nratings",
            nratings);
          Eigen::Matrix<local_scalar_t__,-1,1> prCR =
            Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nratings,
              DUMMY_VAR__);
          current_statement__ = 39;
          stan::model::assign(prCR, stan::math::rep_vector(Tol, nratings),
            "assigning variable prCR");
          current_statement__ = 40;
          stan::math::validate_non_negative_index("prFA", "nratings",
            nratings);
          Eigen::Matrix<local_scalar_t__,-1,1> prFA =
            Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nratings,
              DUMMY_VAR__);
          current_statement__ = 41;
          stan::model::assign(prFA, stan::math::rep_vector(Tol, nratings),
            "assigning variable prFA");
          current_statement__ = 42;
          stan::math::validate_non_negative_index("prM", "nratings", nratings);
          Eigen::Matrix<local_scalar_t__,-1,1> prM =
            Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nratings,
              DUMMY_VAR__);
          current_statement__ = 43;
          stan::model::assign(prM, stan::math::rep_vector(Tol, nratings),
            "assigning variable prM");
          current_statement__ = 44;
          stan::math::validate_non_negative_index("prH", "nratings", nratings);
          Eigen::Matrix<local_scalar_t__,-1,1> prH =
            Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nratings,
              DUMMY_VAR__);
          current_statement__ = 45;
          stan::model::assign(prH, stan::math::rep_vector(Tol, nratings),
            "assigning variable prH");
          current_statement__ = 68;
          for (int i = 1; i <= n_gh; ++i) {
            local_scalar_t__ w = DUMMY_VAR__;
            current_statement__ = 46;
            w = (stan::model::rvalue(gh_weights, "gh_weights",
                   stan::model::index_uni(i))
              * inv_sqrt_pi);
            local_scalar_t__ x_S1 = DUMMY_VAR__;
            current_statement__ = 47;
            x_S1 = (mu_S1 + (sqrt2 *
              stan::model::rvalue(gh_nodes, "gh_nodes",
                stan::model::index_uni(i))));
            local_scalar_t__ log_r_S1 = DUMMY_VAR__;
            current_statement__ = 48;
            log_r_S1 = (0.5 *
              stan::math::log((stan::math::square(x_S1) +
                stan::math::square(eps))));
            local_scalar_t__ x_S2 = DUMMY_VAR__;
            current_statement__ = 49;
            x_S2 = (mu_S2 + (sqrt2 *
              stan::model::rvalue(gh_nodes, "gh_nodes",
                stan::model::index_uni(i))));
            local_scalar_t__ log_r_S2 = DUMMY_VAR__;
            current_statement__ = 50;
            log_r_S2 = (0.5 *
              stan::math::log((stan::math::square(x_S2) +
                stan::math::square(eps))));
            local_scalar_t__ w_cr_S1 = DUMMY_VAR__;
            current_statement__ = 51;
            w_cr_S1 = stan::math::Phi(((c - x_S1) / delta));
            local_scalar_t__ w_fa_S1 = DUMMY_VAR__;
            current_statement__ = 52;
            w_fa_S1 = (1.0 - w_cr_S1);
            local_scalar_t__ w_cr_S2 = DUMMY_VAR__;
            current_statement__ = 53;
            w_cr_S2 = stan::math::Phi(((c - x_S2) / delta));
            local_scalar_t__ w_fa_S2 = DUMMY_VAR__;
            current_statement__ = 54;
            w_fa_S2 = (1.0 - w_cr_S2);
            current_statement__ = 66;
            for (int k = 1; k <= nratings; ++k) {
              local_scalar_t__ p_lo_S1 = DUMMY_VAR__;
              current_statement__ = 55;
              p_lo_S1 = (stan::math::logical_eq(k, 1) ? stan::math::promote_scalar<
                                                          local_scalar_t__>(
                                                          0.0) : stan::math::Phi(
                                                                   ((
                                                                   stan::model::rvalue(
                                                                    log_theta,
                                                                    "log_theta",
                                                                    stan::model::index_uni(
                                                                    (k - 1)))
                                                                   -
                                                                   log_r_S1)
                                                                   / p)));
              local_scalar_t__ p_hi_S1 = DUMMY_VAR__;
              current_statement__ = 56;
              p_hi_S1 = (stan::math::logical_eq(k, nratings) ? stan::math::promote_scalar<
                                                                 local_scalar_t__>(
                                                                 1.0) : 
                stan::math::Phi(
                  ((stan::model::rvalue(log_theta, "log_theta",
                      stan::model::index_uni(k)) - log_r_S1) / p)));
              local_scalar_t__ p_lo_S2 = DUMMY_VAR__;
              current_statement__ = 57;
              p_lo_S2 = (stan::math::logical_eq(k, 1) ? stan::math::promote_scalar<
                                                          local_scalar_t__>(
                                                          0.0) : stan::math::Phi(
                                                                   ((
                                                                   stan::model::rvalue(
                                                                    log_theta,
                                                                    "log_theta",
                                                                    stan::model::index_uni(
                                                                    (k - 1)))
                                                                   -
                                                                   log_r_S2)
                                                                   / p)));
              local_scalar_t__ p_hi_S2 = DUMMY_VAR__;
              current_statement__ = 58;
              p_hi_S2 = (stan::math::logical_eq(k, nratings) ? stan::math::promote_scalar<
                                                                 local_scalar_t__>(
                                                                 1.0) : 
                stan::math::Phi(
                  ((stan::model::rvalue(log_theta, "log_theta",
                      stan::model::index_uni(k)) - log_r_S2) / p)));
              local_scalar_t__ p_k_S1 = DUMMY_VAR__;
              current_statement__ = 59;
              p_k_S1 = stan::math::fmax((p_hi_S1 - p_lo_S1), Tol);
              local_scalar_t__ p_k_S2 = DUMMY_VAR__;
              current_statement__ = 60;
              p_k_S2 = stan::math::fmax((p_hi_S2 - p_lo_S2), Tol);
              current_statement__ = 61;
              stan::model::assign(prCR,
                (stan::model::rvalue(prCR, "prCR",
                   stan::model::index_uni(((nratings + 1) - k))) + ((w *
                w_cr_S1) * p_k_S1)), "assigning variable prCR",
                stan::model::index_uni(((nratings + 1) - k)));
              current_statement__ = 62;
              stan::model::assign(prFA,
                (stan::model::rvalue(prFA, "prFA", stan::model::index_uni(k))
                + ((w * w_fa_S1) * p_k_S1)), "assigning variable prFA",
                stan::model::index_uni(k));
              current_statement__ = 63;
              stan::model::assign(prM,
                (stan::model::rvalue(prM, "prM",
                   stan::model::index_uni(((nratings + 1) - k))) + ((w *
                w_cr_S2) * p_k_S2)), "assigning variable prM",
                stan::model::index_uni(((nratings + 1) - k)));
              current_statement__ = 64;
              stan::model::assign(prH,
                (stan::model::rvalue(prH, "prH", stan::model::index_uni(k)) +
                ((w * w_fa_S2) * p_k_S2)), "assigning variable prH",
                stan::model::index_uni(k));
            }
          }
          current_statement__ = 69;
          lp_accum__.add(stan::math::multinomial_lpmf<false>(
                           stan::model::rvalue(hmetad_counts,
                             "hmetad_counts", stan::model::index_uni(s),
                             stan::model::index_min_max(1, nratings)),
                           stan::math::divide(prCR, stan::math::sum(prCR))));
          current_statement__ = 70;
          lp_accum__.add(stan::math::multinomial_lpmf<false>(
                           stan::model::rvalue(hmetad_counts,
                             "hmetad_counts", stan::model::index_uni(s),
                             stan::model::index_min_max((nratings + 1), (2 *
                               nratings))),
                           stan::math::divide(prFA, stan::math::sum(prFA))));
          current_statement__ = 71;
          lp_accum__.add(stan::math::multinomial_lpmf<false>(
                           stan::model::rvalue(hmetad_counts,
                             "hmetad_counts", stan::model::index_uni(s),
                             stan::model::index_min_max(((2 * nratings) + 1),
                               (3 * nratings))),
                           stan::math::divide(prM, stan::math::sum(prM))));
          current_statement__ = 72;
          lp_accum__.add(stan::math::multinomial_lpmf<false>(
                           stan::model::rvalue(hmetad_counts,
                             "hmetad_counts", stan::model::index_uni(s),
                             stan::model::index_min_max(((3 * nratings) + 1),
                               (4 * nratings))),
                           stan::math::divide(prH, stan::math::sum(prH))));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  // Reverse mode autodiff log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "hmeta_uncertainty_model_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      current_statement__ = 1;
      auto mu_d1 = in__.template read<local_scalar_t__>();
      current_statement__ = 2;
      auto sigma_d1 =
        in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
          lp__);
      current_statement__ = 3;
      auto d1_z =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(nsubj);
      current_statement__ = 4;
      auto mu_c1 = in__.template read<local_scalar_t__>();
      current_statement__ = 5;
      auto sigma_c1 =
        in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
          lp__);
      current_statement__ = 6;
      auto c1_z =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(nsubj);
      current_statement__ = 7;
      auto mu_logPhi = in__.template read<local_scalar_t__>();
      current_statement__ = 8;
      auto beta_logPhi =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(p_cov);
      current_statement__ = 9;
      auto sigma_logPhi =
        in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
          lp__);
      current_statement__ = 10;
      auto logPhi_z =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(nsubj);
      current_statement__ = 11;
      auto log_theta =
        in__.template read_constrain_ordered<
          Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(lp__,
          log_theta_1dim__);
      Eigen::Matrix<local_scalar_t__,-1,1> d1 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nsubj, DUMMY_VAR__);
      current_statement__ = 12;
      stan::model::assign(d1,
        stan::math::add(mu_d1, stan::math::multiply(sigma_d1, d1_z)),
        "assigning variable d1");
      Eigen::Matrix<local_scalar_t__,-1,1> c1 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nsubj, DUMMY_VAR__);
      current_statement__ = 13;
      stan::model::assign(c1,
        stan::math::add(mu_c1, stan::math::multiply(sigma_c1, c1_z)),
        "assigning variable c1");
      Eigen::Matrix<local_scalar_t__,-1,1> phi =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nsubj, DUMMY_VAR__);
      current_statement__ = 19;
      for (int s = 1; s <= nsubj; ++s) {
        local_scalar_t__ eta_s = DUMMY_VAR__;
        current_statement__ = 16;
        eta_s = ((mu_logPhi +
          stan::math::dot_product(beta_logPhi,
            stan::math::transpose(
              stan::model::rvalue(X_cov, "X_cov", stan::model::index_uni(s)))))
          + (sigma_logPhi *
          stan::model::rvalue(logPhi_z, "logPhi_z", stan::model::index_uni(s))));
        current_statement__ = 17;
        stan::model::assign(phi, stan::math::exp(eta_s),
          "assigning variable phi", stan::model::index_uni(s));
      }
      {
        local_scalar_t__ sqrt2 = DUMMY_VAR__;
        current_statement__ = 20;
        sqrt2 = stan::math::sqrt(2.0);
        local_scalar_t__ inv_sqrt_pi = DUMMY_VAR__;
        current_statement__ = 21;
        inv_sqrt_pi = stan::math::inv_sqrt(stan::math::pi());
        current_statement__ = 22;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(mu_d1,
                         static_cast<double>(1), static_cast<double>(2)));
        current_statement__ = 23;
        lp_accum__.add(stan::math::exponential_lpdf<propto__>(sigma_d1,
                         static_cast<double>(1)));
        current_statement__ = 24;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(d1_z,
                         static_cast<double>(0), static_cast<double>(1)));
        current_statement__ = 25;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(mu_c1,
                         static_cast<double>(0), static_cast<double>(1)));
        current_statement__ = 26;
        lp_accum__.add(stan::math::exponential_lpdf<propto__>(sigma_c1,
                         static_cast<double>(1)));
        current_statement__ = 27;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(c1_z,
                         static_cast<double>(0), static_cast<double>(1)));
        current_statement__ = 28;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(mu_logPhi,
                         static_cast<double>(0), static_cast<double>(1)));
        current_statement__ = 29;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(beta_logPhi,
                         static_cast<double>(0), static_cast<double>(1)));
        current_statement__ = 30;
        lp_accum__.add(stan::math::exponential_lpdf<propto__>(sigma_logPhi,
                         static_cast<double>(1)));
        current_statement__ = 31;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(logPhi_z,
                         static_cast<double>(0), static_cast<double>(1)));
        current_statement__ = 32;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(log_theta,
                         static_cast<double>(0), static_cast<double>(1)));
        current_statement__ = 74;
        for (int s = 1; s <= nsubj; ++s) {
          local_scalar_t__ d = DUMMY_VAR__;
          current_statement__ = 33;
          d = stan::model::rvalue(d1, "d1", stan::model::index_uni(s));
          local_scalar_t__ c = DUMMY_VAR__;
          current_statement__ = 34;
          c = stan::model::rvalue(c1, "c1", stan::model::index_uni(s));
          local_scalar_t__ p = DUMMY_VAR__;
          current_statement__ = 35;
          p = stan::model::rvalue(phi, "phi", stan::model::index_uni(s));
          local_scalar_t__ mu_S1 = DUMMY_VAR__;
          current_statement__ = 36;
          mu_S1 = (-(d) / 2.0);
          local_scalar_t__ mu_S2 = DUMMY_VAR__;
          current_statement__ = 37;
          mu_S2 = (d / 2.0);
          current_statement__ = 38;
          stan::math::validate_non_negative_index("prCR", "nratings",
            nratings);
          Eigen::Matrix<local_scalar_t__,-1,1> prCR =
            Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nratings,
              DUMMY_VAR__);
          current_statement__ = 39;
          stan::model::assign(prCR, stan::math::rep_vector(Tol, nratings),
            "assigning variable prCR");
          current_statement__ = 40;
          stan::math::validate_non_negative_index("prFA", "nratings",
            nratings);
          Eigen::Matrix<local_scalar_t__,-1,1> prFA =
            Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nratings,
              DUMMY_VAR__);
          current_statement__ = 41;
          stan::model::assign(prFA, stan::math::rep_vector(Tol, nratings),
            "assigning variable prFA");
          current_statement__ = 42;
          stan::math::validate_non_negative_index("prM", "nratings", nratings);
          Eigen::Matrix<local_scalar_t__,-1,1> prM =
            Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nratings,
              DUMMY_VAR__);
          current_statement__ = 43;
          stan::model::assign(prM, stan::math::rep_vector(Tol, nratings),
            "assigning variable prM");
          current_statement__ = 44;
          stan::math::validate_non_negative_index("prH", "nratings", nratings);
          Eigen::Matrix<local_scalar_t__,-1,1> prH =
            Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nratings,
              DUMMY_VAR__);
          current_statement__ = 45;
          stan::model::assign(prH, stan::math::rep_vector(Tol, nratings),
            "assigning variable prH");
          current_statement__ = 68;
          for (int i = 1; i <= n_gh; ++i) {
            local_scalar_t__ w = DUMMY_VAR__;
            current_statement__ = 46;
            w = (stan::model::rvalue(gh_weights, "gh_weights",
                   stan::model::index_uni(i))
              * inv_sqrt_pi);
            local_scalar_t__ x_S1 = DUMMY_VAR__;
            current_statement__ = 47;
            x_S1 = (mu_S1 + (sqrt2 *
              stan::model::rvalue(gh_nodes, "gh_nodes",
                stan::model::index_uni(i))));
            local_scalar_t__ log_r_S1 = DUMMY_VAR__;
            current_statement__ = 48;
            log_r_S1 = (0.5 *
              stan::math::log((stan::math::square(x_S1) +
                stan::math::square(eps))));
            local_scalar_t__ x_S2 = DUMMY_VAR__;
            current_statement__ = 49;
            x_S2 = (mu_S2 + (sqrt2 *
              stan::model::rvalue(gh_nodes, "gh_nodes",
                stan::model::index_uni(i))));
            local_scalar_t__ log_r_S2 = DUMMY_VAR__;
            current_statement__ = 50;
            log_r_S2 = (0.5 *
              stan::math::log((stan::math::square(x_S2) +
                stan::math::square(eps))));
            local_scalar_t__ w_cr_S1 = DUMMY_VAR__;
            current_statement__ = 51;
            w_cr_S1 = stan::math::Phi(((c - x_S1) / delta));
            local_scalar_t__ w_fa_S1 = DUMMY_VAR__;
            current_statement__ = 52;
            w_fa_S1 = (1.0 - w_cr_S1);
            local_scalar_t__ w_cr_S2 = DUMMY_VAR__;
            current_statement__ = 53;
            w_cr_S2 = stan::math::Phi(((c - x_S2) / delta));
            local_scalar_t__ w_fa_S2 = DUMMY_VAR__;
            current_statement__ = 54;
            w_fa_S2 = (1.0 - w_cr_S2);
            current_statement__ = 66;
            for (int k = 1; k <= nratings; ++k) {
              local_scalar_t__ p_lo_S1 = DUMMY_VAR__;
              current_statement__ = 55;
              p_lo_S1 = (stan::math::logical_eq(k, 1) ? stan::math::promote_scalar<
                                                          local_scalar_t__>(
                                                          0.0) : stan::math::Phi(
                                                                   ((
                                                                   stan::model::rvalue(
                                                                    log_theta,
                                                                    "log_theta",
                                                                    stan::model::index_uni(
                                                                    (k - 1)))
                                                                   -
                                                                   log_r_S1)
                                                                   / p)));
              local_scalar_t__ p_hi_S1 = DUMMY_VAR__;
              current_statement__ = 56;
              p_hi_S1 = (stan::math::logical_eq(k, nratings) ? stan::math::promote_scalar<
                                                                 local_scalar_t__>(
                                                                 1.0) : 
                stan::math::Phi(
                  ((stan::model::rvalue(log_theta, "log_theta",
                      stan::model::index_uni(k)) - log_r_S1) / p)));
              local_scalar_t__ p_lo_S2 = DUMMY_VAR__;
              current_statement__ = 57;
              p_lo_S2 = (stan::math::logical_eq(k, 1) ? stan::math::promote_scalar<
                                                          local_scalar_t__>(
                                                          0.0) : stan::math::Phi(
                                                                   ((
                                                                   stan::model::rvalue(
                                                                    log_theta,
                                                                    "log_theta",
                                                                    stan::model::index_uni(
                                                                    (k - 1)))
                                                                   -
                                                                   log_r_S2)
                                                                   / p)));
              local_scalar_t__ p_hi_S2 = DUMMY_VAR__;
              current_statement__ = 58;
              p_hi_S2 = (stan::math::logical_eq(k, nratings) ? stan::math::promote_scalar<
                                                                 local_scalar_t__>(
                                                                 1.0) : 
                stan::math::Phi(
                  ((stan::model::rvalue(log_theta, "log_theta",
                      stan::model::index_uni(k)) - log_r_S2) / p)));
              local_scalar_t__ p_k_S1 = DUMMY_VAR__;
              current_statement__ = 59;
              p_k_S1 = stan::math::fmax((p_hi_S1 - p_lo_S1), Tol);
              local_scalar_t__ p_k_S2 = DUMMY_VAR__;
              current_statement__ = 60;
              p_k_S2 = stan::math::fmax((p_hi_S2 - p_lo_S2), Tol);
              current_statement__ = 61;
              stan::model::assign(prCR,
                (stan::model::rvalue(prCR, "prCR",
                   stan::model::index_uni(((nratings + 1) - k))) + ((w *
                w_cr_S1) * p_k_S1)), "assigning variable prCR",
                stan::model::index_uni(((nratings + 1) - k)));
              current_statement__ = 62;
              stan::model::assign(prFA,
                (stan::model::rvalue(prFA, "prFA", stan::model::index_uni(k))
                + ((w * w_fa_S1) * p_k_S1)), "assigning variable prFA",
                stan::model::index_uni(k));
              current_statement__ = 63;
              stan::model::assign(prM,
                (stan::model::rvalue(prM, "prM",
                   stan::model::index_uni(((nratings + 1) - k))) + ((w *
                w_cr_S2) * p_k_S2)), "assigning variable prM",
                stan::model::index_uni(((nratings + 1) - k)));
              current_statement__ = 64;
              stan::model::assign(prH,
                (stan::model::rvalue(prH, "prH", stan::model::index_uni(k)) +
                ((w * w_fa_S2) * p_k_S2)), "assigning variable prH",
                stan::model::index_uni(k));
            }
          }
          current_statement__ = 69;
          lp_accum__.add(stan::math::multinomial_lpmf<false>(
                           stan::model::rvalue(hmetad_counts,
                             "hmetad_counts", stan::model::index_uni(s),
                             stan::model::index_min_max(1, nratings)),
                           stan::math::divide(prCR, stan::math::sum(prCR))));
          current_statement__ = 70;
          lp_accum__.add(stan::math::multinomial_lpmf<false>(
                           stan::model::rvalue(hmetad_counts,
                             "hmetad_counts", stan::model::index_uni(s),
                             stan::model::index_min_max((nratings + 1), (2 *
                               nratings))),
                           stan::math::divide(prFA, stan::math::sum(prFA))));
          current_statement__ = 71;
          lp_accum__.add(stan::math::multinomial_lpmf<false>(
                           stan::model::rvalue(hmetad_counts,
                             "hmetad_counts", stan::model::index_uni(s),
                             stan::model::index_min_max(((2 * nratings) + 1),
                               (3 * nratings))),
                           stan::math::divide(prM, stan::math::sum(prM))));
          current_statement__ = 72;
          lp_accum__.add(stan::math::multinomial_lpmf<false>(
                           stan::model::rvalue(hmetad_counts,
                             "hmetad_counts", stan::model::index_uni(s),
                             stan::model::index_min_max(((3 * nratings) + 1),
                               (4 * nratings))),
                           stan::math::divide(prH, stan::math::sum(prH))));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    // suppress unused var warning
    (void) jacobian__;
    static constexpr const char* function__ =
      "hmeta_uncertainty_model_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      current_statement__ = 1;
      auto mu_d1 = in__.template read<local_scalar_t__>();
      current_statement__ = 2;
      auto sigma_d1 =
        in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
          lp__);
      current_statement__ = 3;
      auto d1_z =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(nsubj);
      current_statement__ = 4;
      auto mu_c1 = in__.template read<local_scalar_t__>();
      current_statement__ = 5;
      auto sigma_c1 =
        in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
          lp__);
      current_statement__ = 6;
      auto c1_z =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(nsubj);
      current_statement__ = 7;
      auto mu_logPhi = in__.template read<local_scalar_t__>();
      current_statement__ = 8;
      auto beta_logPhi =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(p_cov);
      current_statement__ = 9;
      auto sigma_logPhi =
        in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
          lp__);
      current_statement__ = 10;
      auto logPhi_z =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(nsubj);
      current_statement__ = 11;
      auto log_theta =
        in__.template read_constrain_ordered<
          Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(lp__,
          log_theta_1dim__);
      Eigen::Matrix<double,-1,1> d1 =
        Eigen::Matrix<double,-1,1>::Constant(nsubj,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> c1 =
        Eigen::Matrix<double,-1,1>::Constant(nsubj,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> phi =
        Eigen::Matrix<double,-1,1>::Constant(nsubj,
          std::numeric_limits<double>::quiet_NaN());
      out__.write(mu_d1);
      out__.write(sigma_d1);
      out__.write(d1_z);
      out__.write(mu_c1);
      out__.write(sigma_c1);
      out__.write(c1_z);
      out__.write(mu_logPhi);
      out__.write(beta_logPhi);
      out__.write(sigma_logPhi);
      out__.write(logPhi_z);
      out__.write(log_theta);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 12;
      stan::model::assign(d1,
        stan::math::add(mu_d1, stan::math::multiply(sigma_d1, d1_z)),
        "assigning variable d1");
      current_statement__ = 13;
      stan::model::assign(c1,
        stan::math::add(mu_c1, stan::math::multiply(sigma_c1, c1_z)),
        "assigning variable c1");
      current_statement__ = 19;
      for (int s = 1; s <= nsubj; ++s) {
        double eta_s = std::numeric_limits<double>::quiet_NaN();
        current_statement__ = 16;
        eta_s = ((mu_logPhi +
          stan::math::dot_product(beta_logPhi,
            stan::math::transpose(
              stan::model::rvalue(X_cov, "X_cov", stan::model::index_uni(s)))))
          + (sigma_logPhi *
          stan::model::rvalue(logPhi_z, "logPhi_z", stan::model::index_uni(s))));
        current_statement__ = 17;
        stan::model::assign(phi, stan::math::exp(eta_s),
          "assigning variable phi", stan::model::index_uni(s));
      }
      if (emit_transformed_parameters__) {
        out__.write(d1);
        out__.write(c1);
        out__.write(phi);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
      double group_phi = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 15;
      group_phi = stan::math::exp(mu_logPhi);
      out__.write(group_phi);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      local_scalar_t__ mu_d1 = DUMMY_VAR__;
      current_statement__ = 1;
      mu_d1 = in__.read<local_scalar_t__>();
      out__.write(mu_d1);
      local_scalar_t__ sigma_d1 = DUMMY_VAR__;
      current_statement__ = 2;
      sigma_d1 = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, sigma_d1);
      Eigen::Matrix<local_scalar_t__,-1,1> d1_z =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nsubj, DUMMY_VAR__);
      current_statement__ = 3;
      stan::model::assign(d1_z,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(nsubj),
        "assigning variable d1_z");
      out__.write(d1_z);
      local_scalar_t__ mu_c1 = DUMMY_VAR__;
      current_statement__ = 4;
      mu_c1 = in__.read<local_scalar_t__>();
      out__.write(mu_c1);
      local_scalar_t__ sigma_c1 = DUMMY_VAR__;
      current_statement__ = 5;
      sigma_c1 = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, sigma_c1);
      Eigen::Matrix<local_scalar_t__,-1,1> c1_z =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nsubj, DUMMY_VAR__);
      current_statement__ = 6;
      stan::model::assign(c1_z,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(nsubj),
        "assigning variable c1_z");
      out__.write(c1_z);
      local_scalar_t__ mu_logPhi = DUMMY_VAR__;
      current_statement__ = 7;
      mu_logPhi = in__.read<local_scalar_t__>();
      out__.write(mu_logPhi);
      Eigen::Matrix<local_scalar_t__,-1,1> beta_logPhi =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(p_cov, DUMMY_VAR__);
      current_statement__ = 8;
      stan::model::assign(beta_logPhi,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(p_cov),
        "assigning variable beta_logPhi");
      out__.write(beta_logPhi);
      local_scalar_t__ sigma_logPhi = DUMMY_VAR__;
      current_statement__ = 9;
      sigma_logPhi = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, sigma_logPhi);
      Eigen::Matrix<local_scalar_t__,-1,1> logPhi_z =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nsubj, DUMMY_VAR__);
      current_statement__ = 10;
      stan::model::assign(logPhi_z,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(nsubj),
        "assigning variable logPhi_z");
      out__.write(logPhi_z);
      Eigen::Matrix<local_scalar_t__,-1,1> log_theta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(log_theta_1dim__,
          DUMMY_VAR__);
      current_statement__ = 11;
      stan::model::assign(log_theta,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(log_theta_1dim__),
        "assigning variable log_theta");
      out__.write_free_ordered(log_theta);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "mu_d1", "double",
        std::vector<size_t>{});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "sigma_d1",
        "double", std::vector<size_t>{});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "d1_z", "double",
        std::vector<size_t>{static_cast<size_t>(nsubj)});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization", "mu_c1", "double",
        std::vector<size_t>{});
      current_statement__ = 5;
      context__.validate_dims("parameter initialization", "sigma_c1",
        "double", std::vector<size_t>{});
      current_statement__ = 6;
      context__.validate_dims("parameter initialization", "c1_z", "double",
        std::vector<size_t>{static_cast<size_t>(nsubj)});
      current_statement__ = 7;
      context__.validate_dims("parameter initialization", "mu_logPhi",
        "double", std::vector<size_t>{});
      current_statement__ = 8;
      context__.validate_dims("parameter initialization", "beta_logPhi",
        "double", std::vector<size_t>{static_cast<size_t>(p_cov)});
      current_statement__ = 9;
      context__.validate_dims("parameter initialization", "sigma_logPhi",
        "double", std::vector<size_t>{});
      current_statement__ = 10;
      context__.validate_dims("parameter initialization", "logPhi_z",
        "double", std::vector<size_t>{static_cast<size_t>(nsubj)});
      current_statement__ = 11;
      context__.validate_dims("parameter initialization", "log_theta",
        "double", std::vector<size_t>{static_cast<size_t>(log_theta_1dim__)});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ mu_d1 = DUMMY_VAR__;
      current_statement__ = 1;
      mu_d1 = context__.vals_r("mu_d1")[(1 - 1)];
      out__.write(mu_d1);
      local_scalar_t__ sigma_d1 = DUMMY_VAR__;
      current_statement__ = 2;
      sigma_d1 = context__.vals_r("sigma_d1")[(1 - 1)];
      out__.write_free_lb(0, sigma_d1);
      Eigen::Matrix<local_scalar_t__,-1,1> d1_z =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nsubj, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> d1_z_flat__;
        current_statement__ = 3;
        d1_z_flat__ = context__.vals_r("d1_z");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= nsubj; ++sym1__) {
          stan::model::assign(d1_z, d1_z_flat__[(pos__ - 1)],
            "assigning variable d1_z", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      out__.write(d1_z);
      local_scalar_t__ mu_c1 = DUMMY_VAR__;
      current_statement__ = 4;
      mu_c1 = context__.vals_r("mu_c1")[(1 - 1)];
      out__.write(mu_c1);
      local_scalar_t__ sigma_c1 = DUMMY_VAR__;
      current_statement__ = 5;
      sigma_c1 = context__.vals_r("sigma_c1")[(1 - 1)];
      out__.write_free_lb(0, sigma_c1);
      Eigen::Matrix<local_scalar_t__,-1,1> c1_z =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nsubj, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> c1_z_flat__;
        current_statement__ = 6;
        c1_z_flat__ = context__.vals_r("c1_z");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= nsubj; ++sym1__) {
          stan::model::assign(c1_z, c1_z_flat__[(pos__ - 1)],
            "assigning variable c1_z", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      out__.write(c1_z);
      local_scalar_t__ mu_logPhi = DUMMY_VAR__;
      current_statement__ = 7;
      mu_logPhi = context__.vals_r("mu_logPhi")[(1 - 1)];
      out__.write(mu_logPhi);
      Eigen::Matrix<local_scalar_t__,-1,1> beta_logPhi =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(p_cov, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> beta_logPhi_flat__;
        current_statement__ = 8;
        beta_logPhi_flat__ = context__.vals_r("beta_logPhi");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= p_cov; ++sym1__) {
          stan::model::assign(beta_logPhi, beta_logPhi_flat__[(pos__ - 1)],
            "assigning variable beta_logPhi", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      out__.write(beta_logPhi);
      local_scalar_t__ sigma_logPhi = DUMMY_VAR__;
      current_statement__ = 9;
      sigma_logPhi = context__.vals_r("sigma_logPhi")[(1 - 1)];
      out__.write_free_lb(0, sigma_logPhi);
      Eigen::Matrix<local_scalar_t__,-1,1> logPhi_z =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nsubj, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> logPhi_z_flat__;
        current_statement__ = 10;
        logPhi_z_flat__ = context__.vals_r("logPhi_z");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= nsubj; ++sym1__) {
          stan::model::assign(logPhi_z, logPhi_z_flat__[(pos__ - 1)],
            "assigning variable logPhi_z", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      out__.write(logPhi_z);
      Eigen::Matrix<local_scalar_t__,-1,1> log_theta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(log_theta_1dim__,
          DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> log_theta_flat__;
        current_statement__ = 11;
        log_theta_flat__ = context__.vals_r("log_theta");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= log_theta_1dim__; ++sym1__) {
          stan::model::assign(log_theta, log_theta_flat__[(pos__ - 1)],
            "assigning variable log_theta", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_ordered(log_theta);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"mu_d1", "sigma_d1", "d1_z", "mu_c1",
                "sigma_c1", "c1_z", "mu_logPhi", "beta_logPhi",
                "sigma_logPhi", "logPhi_z", "log_theta"};
    if (emit_transformed_parameters__) {
      std::vector<std::string> temp{"d1", "c1", "phi"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::string> temp{"group_phi"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
                std::vector<size_t>{},
                std::vector<size_t>{static_cast<size_t>(nsubj)},
                std::vector<size_t>{}, std::vector<size_t>{},
                std::vector<size_t>{static_cast<size_t>(nsubj)},
                std::vector<size_t>{},
                std::vector<size_t>{static_cast<size_t>(p_cov)},
                std::vector<size_t>{},
                std::vector<size_t>{static_cast<size_t>(nsubj)},
                std::vector<size_t>{static_cast<size_t>(log_theta_1dim__)}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(nsubj)},
             std::vector<size_t>{static_cast<size_t>(nsubj)},
             std::vector<size_t>{static_cast<size_t>(nsubj)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::vector<size_t>> temp{std::vector<size_t>{}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "mu_d1");
    param_names__.emplace_back(std::string() + "sigma_d1");
    for (int sym1__ = 1; sym1__ <= nsubj; ++sym1__) {
      param_names__.emplace_back(std::string() + "d1_z" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "mu_c1");
    param_names__.emplace_back(std::string() + "sigma_c1");
    for (int sym1__ = 1; sym1__ <= nsubj; ++sym1__) {
      param_names__.emplace_back(std::string() + "c1_z" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "mu_logPhi");
    for (int sym1__ = 1; sym1__ <= p_cov; ++sym1__) {
      param_names__.emplace_back(std::string() + "beta_logPhi" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "sigma_logPhi");
    for (int sym1__ = 1; sym1__ <= nsubj; ++sym1__) {
      param_names__.emplace_back(std::string() + "logPhi_z" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= log_theta_1dim__; ++sym1__) {
      param_names__.emplace_back(std::string() + "log_theta" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= nsubj; ++sym1__) {
        param_names__.emplace_back(std::string() + "d1" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= nsubj; ++sym1__) {
        param_names__.emplace_back(std::string() + "c1" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= nsubj; ++sym1__) {
        param_names__.emplace_back(std::string() + "phi" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {
      param_names__.emplace_back(std::string() + "group_phi");
    }
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "mu_d1");
    param_names__.emplace_back(std::string() + "sigma_d1");
    for (int sym1__ = 1; sym1__ <= nsubj; ++sym1__) {
      param_names__.emplace_back(std::string() + "d1_z" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "mu_c1");
    param_names__.emplace_back(std::string() + "sigma_c1");
    for (int sym1__ = 1; sym1__ <= nsubj; ++sym1__) {
      param_names__.emplace_back(std::string() + "c1_z" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "mu_logPhi");
    for (int sym1__ = 1; sym1__ <= p_cov; ++sym1__) {
      param_names__.emplace_back(std::string() + "beta_logPhi" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "sigma_logPhi");
    for (int sym1__ = 1; sym1__ <= nsubj; ++sym1__) {
      param_names__.emplace_back(std::string() + "logPhi_z" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= log_theta_1dim__; ++sym1__) {
      param_names__.emplace_back(std::string() + "log_theta" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= nsubj; ++sym1__) {
        param_names__.emplace_back(std::string() + "d1" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= nsubj; ++sym1__) {
        param_names__.emplace_back(std::string() + "c1" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= nsubj; ++sym1__) {
        param_names__.emplace_back(std::string() + "phi" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {
      param_names__.emplace_back(std::string() + "group_phi");
    }
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"mu_d1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_d1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"d1_z\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(nsubj) + "},\"block\":\"parameters\"},{\"name\":\"mu_c1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_c1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"c1_z\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(nsubj) + "},\"block\":\"parameters\"},{\"name\":\"mu_logPhi\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta_logPhi\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(p_cov) + "},\"block\":\"parameters\"},{\"name\":\"sigma_logPhi\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"logPhi_z\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(nsubj) + "},\"block\":\"parameters\"},{\"name\":\"log_theta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(log_theta_1dim__) + "},\"block\":\"parameters\"},{\"name\":\"d1\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(nsubj) + "},\"block\":\"transformed_parameters\"},{\"name\":\"c1\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(nsubj) + "},\"block\":\"transformed_parameters\"},{\"name\":\"phi\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(nsubj) + "},\"block\":\"transformed_parameters\"},{\"name\":\"group_phi\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"mu_d1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_d1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"d1_z\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(nsubj) + "},\"block\":\"parameters\"},{\"name\":\"mu_c1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_c1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"c1_z\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(nsubj) + "},\"block\":\"parameters\"},{\"name\":\"mu_logPhi\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta_logPhi\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(p_cov) + "},\"block\":\"parameters\"},{\"name\":\"sigma_logPhi\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"logPhi_z\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(nsubj) + "},\"block\":\"parameters\"},{\"name\":\"log_theta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(log_theta_1dim__) + "},\"block\":\"parameters\"},{\"name\":\"d1\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(nsubj) + "},\"block\":\"transformed_parameters\"},{\"name\":\"c1\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(nsubj) + "},\"block\":\"transformed_parameters\"},{\"name\":\"phi\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(nsubj) + "},\"block\":\"transformed_parameters\"},{\"name\":\"group_phi\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = 1 + 1 + nsubj + 1 + 1 + nsubj + 1 + p_cov + 1
      + nsubj + log_theta_1dim__;
    const size_t num_transformed = emit_transformed_parameters * (nsubj +
      nsubj + nsubj);
    const size_t num_gen_quantities = emit_generated_quantities * (1);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = 1 + 1 + nsubj + 1 + 1 + nsubj + 1 + p_cov + 1
      + nsubj + log_theta_1dim__;
    const size_t num_transformed = emit_transformed_parameters * (nsubj +
      nsubj + nsubj);
    const size_t num_gen_quantities = emit_generated_quantities * (1);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = hmeta_uncertainty_model_namespace::hmeta_uncertainty_model;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return hmeta_uncertainty_model_namespace::profiles__;
}
#endif